agents:
  queue: "compile"
env:
  RUNREAL_PROJECT_PATH: $BUILDKITE_BUILD_CHECKOUT_PATH
  RUNREAL_BUILD_PATH: $BUILDKITE_BUILD_CHECKOUT_PATH\.dist
  RUNREAL_ENGINE_PATH: $BUILDKITE_BUILD_PATH\UnrealEngine
  RUNREAL_ENGINE_CACHE_PATH: $BUILDKITE_BUILD_PATH\.cache
  RUNREAL_GIT_DEPENDENCIES_CACHE_PATH: $BUILDKITE_BUILD_PATH\.gitdepscache
  RUNREAL_GIT_MIRRORS_PATH: $BUILDKITE_BUILD_PATH\.mirrors
steps:
  - label: ":windows: Build CkPluginsEditor"
    command: "runreal workflow exec 'Build Editor' --mode buildkite"
    plugins:
      - chainkemists/runreal
      - git-clean#v1.0.0:
          flags: "-fdqx --exclude=*Intermediate/ --exclude=*Binaries/ --exclude=Saved/"
  - label: ":windows: Build CkPluginsGame"
    command: "runreal workflow exec 'Build Game' --mode buildkite"
    plugins:
      - chainkemists/runreal
      - git-clean#v1.0.0:
          flags: "-fdqx --exclude=*Intermediate/ --exclude=*Binaries/ --exclude=Saved/"