;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=True
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/CkTests/GameplayTags_Tests_CkDT.GameplayTags_Tests_CkDT
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Ck.Gyms.Ability.BulletCostNotMet",NewTagName="Ck.Gyms.Ability.FireProjectileCostNotMet")
+GameplayTagRedirects=(OldTagName="Ck.Gyms.Ability.BulletCost",NewTagName="Ck.Gyms.Ability.FireProjectileCost")
+GameplayTagList=(Tag="AudioGym.Advanced.Achievement.Fanfare",DevComment="")
+GameplayTagList=(Tag="AudioGym.Advanced.Concurrency.Thunder",DevComment="")
+GameplayTagList=(Tag="AudioGym.Advanced.Interface.Pickup",DevComment="")
+GameplayTagList=(Tag="AudioGym.Advanced.Music.Orchestral",DevComment="")
+GameplayTagList=(Tag="AudioGym.Advanced.Pickup",DevComment="Added via code")
+GameplayTagList=(Tag="AudioGym.Advanced.Probe.Station",DevComment="Added via code")
+GameplayTagList=(Tag="AudioGym.Simple.BackgroundMusic",DevComment="")
+GameplayTagList=(Tag="AudioGym.Simple.SpatialAudio",DevComment="")
+GameplayTagList=(Tag="ByteAttribute.Armor",DevComment="Added via code")
+GameplayTagList=(Tag="ByteAttribute.Damage",DevComment="Added via code")
+GameplayTagList=(Tag="ByteAttribute.Defense",DevComment="Added via code")
+GameplayTagList=(Tag="ByteAttribute.Health",DevComment="Added via code")
+GameplayTagList=(Tag="ByteAttribute.PowerLevel",DevComment="Added via code")
+GameplayTagList=(Tag="ByteAttribute.Stamina",DevComment="Added via code")
+GameplayTagList=(Tag="Combat.Attack",DevComment="Added via code")
+GameplayTagList=(Tag="Combat.Defense",DevComment="Added via code")
+GameplayTagList=(Tag="Message.Ck_Message_AttributeGym_ResetAttributes",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_AttributeGym_TestBoundaries",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.CkGym_Station_SpawnParams_Payload",DevComment="Added via the Messaging Node")
+GameplayTagList=(Tag="Modifier.Armor",DevComment="Added via code")
+GameplayTagList=(Tag="Modifier.Buff",DevComment="Added via code")
+GameplayTagList=(Tag="Modifier.Enchant",DevComment="Added via code")
+GameplayTagList=(Tag="Modifier.Enchantment",DevComment="Added via code")
+GameplayTagList=(Tag="Modifier.Shield",DevComment="Added via code")
+GameplayTagList=(Tag="Modifier.Weapon",DevComment="Added via code")
+GameplayTagList=(Tag="Player.Probe",DevComment="Added via code")
+GameplayTagList=(Tag="ResolverDataBundle.Default",DevComment="")
+GameplayTagList=(Tag="ResolverPhase.Ck.Gyms.Default",DevComment="")
+GameplayTagList=(Tag="RPG.Agility",DevComment="Added via code")
+GameplayTagList=(Tag="RPG.Intelligence",DevComment="Added via code")
+GameplayTagList=(Tag="RPG.Strength",DevComment="Added via code")
+GameplayTagList=(Tag="Test.SignalBinding",DevComment="Added via code")
+GameplayTagList=(Tag="Test.ValueRetrieval",DevComment="Added via code")

