;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=True
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/CkTests/GameplayTags_Tests_CkDT.GameplayTags_Tests_CkDT
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Ck.Gyms.Ability.BulletCostNotMet",NewTagName="Ck.Gyms.Ability.FireProjectileCostNotMet")
+GameplayTagRedirects=(OldTagName="Ck.Gyms.Ability.BulletCost",NewTagName="Ck.Gyms.Ability.FireProjectileCost")
+GameplayTagList=(Tag="ActorRelay.Cue.Audio",DevComment="Added via code")
+GameplayTagList=(Tag="ActorRelay.Cue.Generic",DevComment="Added via code")
+GameplayTagList=(Tag="ActorRelay.Cue.Objective",DevComment="Added via code")
+GameplayTagList=(Tag="ActorRelay.Cue.Vfx",DevComment="Added via code")
+GameplayTagList=(Tag="Attribute.Armor",DevComment="Added via code")
+GameplayTagList=(Tag="Attribute.Health",DevComment="Added via code")
+GameplayTagList=(Tag="Attribute.Velocity",DevComment="Added via code")
+GameplayTagList=(Tag="AudioGym.Advanced.Achievement.Fanfare",DevComment="")
+GameplayTagList=(Tag="AudioGym.Advanced.Concurrency.Thunder",DevComment="")
+GameplayTagList=(Tag="AudioGym.Advanced.Interface.Pickup",DevComment="")
+GameplayTagList=(Tag="AudioGym.Advanced.Music.Orchestral",DevComment="")
+GameplayTagList=(Tag="AudioGym.Advanced.Pickup",DevComment="Added via code")
+GameplayTagList=(Tag="AudioGym.Advanced.Probe.Station",DevComment="Added via code")
+GameplayTagList=(Tag="AudioGym.Advanced.Station.Basic",DevComment="Added via code")
+GameplayTagList=(Tag="AudioGym.Simple.BackgroundMusic",DevComment="")
+GameplayTagList=(Tag="AudioGym.Simple.SpatialAudio",DevComment="")
+GameplayTagList=(Tag="ByteAttribute.Armor",DevComment="Added via code")
+GameplayTagList=(Tag="ByteAttribute.Damage",DevComment="Added via code")
+GameplayTagList=(Tag="ByteAttribute.Defense",DevComment="Added via code")
+GameplayTagList=(Tag="ByteAttribute.Health",DevComment="Added via code")
+GameplayTagList=(Tag="ByteAttribute.PowerLevel",DevComment="Added via code")
+GameplayTagList=(Tag="ByteAttribute.Shield",DevComment="Added via code")
+GameplayTagList=(Tag="ByteAttribute.Stamina",DevComment="Added via code")
+GameplayTagList=(Tag="Combat.Attack",DevComment="Added via code")
+GameplayTagList=(Tag="Combat.Defense",DevComment="Added via code")
+GameplayTagList=(Tag="CueGym.Concurrency.Multiple",DevComment="")
+GameplayTagList=(Tag="CueGym.Concurrency.Restart",DevComment="")
+GameplayTagList=(Tag="CueGym.Lifetime.AfterOneFrame",DevComment="")
+GameplayTagList=(Tag="CueGym.Lifetime.Custom",DevComment="")
+GameplayTagList=(Tag="CueGym.Lifetime.Persistent",DevComment="")
+GameplayTagList=(Tag="CueGym.Lifetime.Timed",DevComment="")
+GameplayTagList=(Tag="CueGym.Owner.RequireValid",DevComment="")
+GameplayTagList=(Tag="CueGym.Owner.SkipInvalid",DevComment="")
+GameplayTagList=(Tag="CueGym.OwnerDestruction.Attached",DevComment="")
+GameplayTagList=(Tag="CueGym.Restart.Restartable",DevComment="")
+GameplayTagList=(Tag="CueGym.Transient.NoOwner",DevComment="")
+GameplayTagList=(Tag="FloatAttribute.Armor",DevComment="Added via code")
+GameplayTagList=(Tag="FloatAttribute.Counter",DevComment="Added via code")
+GameplayTagList=(Tag="FloatAttribute.Damage",DevComment="Added via code")
+GameplayTagList=(Tag="FloatAttribute.Defense",DevComment="Added via code")
+GameplayTagList=(Tag="FloatAttribute.Energy",DevComment="Added via code")
+GameplayTagList=(Tag="FloatAttribute.Health",DevComment="Added via code")
+GameplayTagList=(Tag="FloatAttribute.Mana",DevComment="Added via code")
+GameplayTagList=(Tag="FloatAttribute.PowerLevel",DevComment="Added via code")
+GameplayTagList=(Tag="FloatAttribute.Signal",DevComment="Added via code")
+GameplayTagList=(Tag="FloatAttribute.Stamina",DevComment="Added via code")
+GameplayTagList=(Tag="FloatAttribute.Test",DevComment="Added via code")
+GameplayTagList=(Tag="IntegerAttribute.Armor",DevComment="Added via code")
+GameplayTagList=(Tag="IntegerAttribute.Damage",DevComment="Added via code")
+GameplayTagList=(Tag="IntegerAttribute.Experience",DevComment="Added via code")
+GameplayTagList=(Tag="IntegerAttribute.Health",DevComment="Added via code")
+GameplayTagList=(Tag="IntegerAttribute.PowerLevel",DevComment="Added via code")
+GameplayTagList=(Tag="IntegerAttribute.Resource",DevComment="Added via code")
+GameplayTagList=(Tag="InteractionChannel.InteractionGym.Default",DevComment="Added via code")
+GameplayTagList=(Tag="InteractionChannel.InteractionGym.Secondary",DevComment="Added via code")
+GameplayTagList=(Tag="InteractionIntent.InteractionGym.Use",DevComment="Added via code")
+GameplayTagList=(Tag="Inventory.Backpack",DevComment="Added via code")
+GameplayTagList=(Tag="Inventory.Bounded",DevComment="Added via code")
+GameplayTagList=(Tag="Inventory.Equipment",DevComment="Added via code")
+GameplayTagList=(Tag="Item.Ammo",DevComment="Added via code")
+GameplayTagList=(Tag="Item.Consumable",DevComment="Added via code")
+GameplayTagList=(Tag="Item.Defense",DevComment="Added via code")
+GameplayTagList=(Tag="Item.Equipment",DevComment="Added via code")
+GameplayTagList=(Tag="Item.Melee",DevComment="Added via code")
+GameplayTagList=(Tag="Item.Potion",DevComment="Added via code")
+GameplayTagList=(Tag="Item.Quest",DevComment="Added via code")
+GameplayTagList=(Tag="Item.Rarity.Legendary",DevComment="Added via code")
+GameplayTagList=(Tag="Item.Rarity.Rare",DevComment="Added via code")
+GameplayTagList=(Tag="Item.Weapon",DevComment="Added via code")
+GameplayTagList=(Tag="Message.Ck_Message_AttributeGym_AutoSet",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_AttributeGym_ResetAttributes",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_AttributeGym_SetArmor",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_AttributeGym_SetHealth",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_AttributeGym_SetVelocity",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_AttributeGym_TestBoundaries",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_AttributeGym_UpdateAttributes",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_FloatGym_ToggleRefill",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_IntegerGym_AddModifier",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_IntegerGym_ClearModifiers",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_IntegerGym_RemoveModifier",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_IntegerGym_ResetAttributes",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_IntegerGym_SetArmor",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_IntegerGym_SetExperience",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_IntegerGym_SetHealth",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_IntegerGym_TestBoundaries",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InteractionGym_AddTargets",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InteractionGym_AttemptValidation",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InteractionGym_AutoSet",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InteractionGym_CancelManual",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InteractionGym_Command",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InteractionGym_EndManualFail",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InteractionGym_EndManualSuccess",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InteractionGym_InitiateResolution",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InteractionGym_RemoveTargets",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InteractionGym_StartIntent",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InteractionGym_StartManual",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InteractionGym_StartTimed",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InteractionGym_StopIntent",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InteractionGym_ToggleCustomValidation",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InteractionGym_ToggleEnabled",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InteractionGym_TriggerInstant",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InvGym_AddItemAt",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InvGym_AddItemByDef",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InvGym_AddTag",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InvGym_AutoSet",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InvGym_AutoToggle",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InvGym_OverrideBounds",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InvGym_RemoveFirst",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InvGym_RemoveTag",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InvGym_ShelfLoop",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InvGym_ShelfLoot",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InvGym_ShelfReset",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InvGym_ShelfStock",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InvGym_SortInventory",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InvGym_SplitFirst",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_InvGym_StackFirstTwo",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_MessagingGym_Alert",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_MessagingGym_Ping",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_MessagingGym_Pong",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_MessagingGym_Reset",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.Ck_Message_MessagingGym_ToggleBind",DevComment="Generated from a Message payload definition")
+GameplayTagList=(Tag="Message.CkGym_Station_SpawnParams_Payload",DevComment="Added via the Messaging Node")
+GameplayTagList=(Tag="Modifier.Armor",DevComment="Added via code")
+GameplayTagList=(Tag="Modifier.Buff",DevComment="Added via code")
+GameplayTagList=(Tag="Modifier.Enchant",DevComment="Added via code")
+GameplayTagList=(Tag="Modifier.Enchantment",DevComment="Added via code")
+GameplayTagList=(Tag="Modifier.Shield",DevComment="Added via code")
+GameplayTagList=(Tag="Modifier.Weapon",DevComment="Added via code")
+GameplayTagList=(Tag="Player.Probe",DevComment="Added via code")
+GameplayTagList=(Tag="ResolverDataBundle.Default",DevComment="")
+GameplayTagList=(Tag="ResolverDataBundle.InteractionGym.Damage",DevComment="Added via Angelscript auto resolve")
+GameplayTagList=(Tag="ResolverPhase.Ck.Gyms.Default",DevComment="")
+GameplayTagList=(Tag="ResolverPhase.InteractionGym.Apply",DevComment="Added via code")
+GameplayTagList=(Tag="ResolverPhase.InteractionGym.Calculate",DevComment="Added via code")
+GameplayTagList=(Tag="RPG.Agility",DevComment="Added via code")
+GameplayTagList=(Tag="RPG.Intelligence",DevComment="Added via code")
+GameplayTagList=(Tag="RPG.Strength",DevComment="Added via code")
+GameplayTagList=(Tag="Test.SignalBinding",DevComment="Added via code")
+GameplayTagList=(Tag="Test.ValueRetrieval",DevComment="Added via code")

